### ISSUE TITLE
Returns only URL & Transcript

### ISSUE THREAD

**Issue by ckfchampion** [wesley4546/youtubetranscription#1]
Hi, first off - this is amazing thank you! I'm very new to this, but I was able to get it working. However, it seems only to return the YouTube URL and transcript and the other information returns with 'No Video Information Found.' Not sure if you've run into the problem too?

**Comment by wesley4546** [comment]
Hello! I'm also sort of new to this but it has been an adventure! Depending on the YouTube URL generated from the keyword put in, if there isn't information to be found from the video (if it maybe was a live stream or any other thing form YouTube that isn't a video) it will return that. 

What keyword did you use and what URLs are showing no video information?

**Comment by ckfchampion** [comment]
Hi, well that makes both of us - we can combine our brains :) So the two keywords I have tried are 'Biossance' and 'Drunk Elephant'. For the first keyword it returned the URL and transcript perfectly (https://www.youtube.com/watch?v=zEX07KAjFcY) and when I click the video there is a lot of info that could imported. Seeing as it's happening with all of the videos, it seems unlikely that it's the videos that don't contain information.

**Comment by wesley4546** [comment]
So I went ahead and ran that link you gave me (https://www.youtube.com/watch?v=zEX07KAjFcY) through the function `get_video_info()` which is what is used in the main script and got the information: 

`{'title': 'The Truth About Biossance', 'views': 170897, 'description': 'COME MEET ME | Seattle, Los Angeles, & ChicagoMeet-Up Dates & Times: https://bit.ly/2LL8utCYour FREE Skin Care Course: https://bit.ly/2uX7x8ySubscribe to learn how to perfect YOUR skin care routine: https://www.youtube.com/hyramPRODUCTS MENTIONED🌹 Rose Vegan Lip Balm: https://shopstyle.it/l/bbwzR🐠 Marine Algae Eye Cream: https://shopstyle.it/l/bbwzN❄️ Omega Repair Cream: http://bit.ly/343OBnK🌱 100% Squalane Oil: http://bit.ly/2rrbCnt🌊 Probiotic Gel Moisturizer: http://bit.ly/2KQQ4aiVIDEOS MENTIONEDThe Best Skin Care of 2019: https://bit.ly/2rieYJCThank you Biossance for sending me a few of these items!Be sure to SUBSCRIBE to my channel to learn how to perfect your skin care routine every week! :)___FOLLOW MEInstagram (@SkinCarebyHyram): https://bit.ly/362vLzHTwitter (@SkinCarebyHyram): https://bit.ly/2JfRM4nBUSINESS/PR INQUIRIES: info@skincarebyhyram.com*Some links may be affiliate links that help me earn a small commission from your purchase. Each purchase supports me to keep working as hard as I can to make videos for you guys! Thank you for the support :)*', 'date_published': 'Published on Dec 8, 2019', 'likes': 5144, 'dislikes': 68, 'channel': {'name': 'Hyram', 'url': 'https://www.youtube.com/channel/UC2sYit3cZ2CuD_8FHYH7O_Q', 'subscribers': '1.58M'}}`

So it seemed to work with that URL. 

Can you send me the CSV file that was outputted so I can take a look?

**Comment by ckfchampion** [comment]
Yes, that's what should be outputting indeed. Odd that it's not with me (oh, also this doesn't work with a VPN, not sure if that's something I should mention or not). Here you go: 

[youtubetranscription-csv.zip](https://github.com/wesley4546/youtubetranscription/files/4624286/youtubetranscription-csv.zip)

**Comment by wesley4546** [comment]
I'm looking into it now and I'll post a response if I find anything.

Thank you for bringing this to my attention!

**Comment by wesley4546** [comment]
I went ahead and ran the "Biossance" keyword in the program and was given a file _with_ most of the videos having information (Attached below)

I noticed from the zip file you sent that it had a MACOSX file - I'm running this program on Windows 10 and with the PyCharm IDE. I'll look into doing this on my Mac laptop and see how my result vary (I won't be able to do this until later tonight so I'll update you as soon as I can).

[Biossance_videos.zip](https://github.com/wesley4546/youtubetranscription/files/4624335/Biossance_videos.zip)

**Comment by ckfchampion** [comment]
Yes, indeed that's how I expected it to return. I'm running it on Mac Catalina macOS 10.15.4 (just the built-in terminal), I'll look into PyCharm IDE as well.

**Comment by wesley4546** [comment]
Do me a favor and make sure you have all the package installations within the `requirements.txt`

**Comment by ckfchampion** [comment]
Confirmed, I ran it again and it says `Requirement already satisfied`

**Comment by wesley4546** [comment]
What version of Python are you running?

**Comment by ckfchampion** [comment]
Python 3.7.6

**Comment by wesley4546** [comment]
I was able to run this on my Mac with the same version as you and it was able to work. I am using python 3.8.2. I've done a little bit of bug fixing as well. If you're able to try again - let me know if you run into the same issue.

**Comment by ckfchampion** [comment]
It must be something I am doing wrong then, when I run it with python3 I get this error: ```
 /Documents/youtubetranscription-master/source/youtubescraper.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

I'll have to read a few more tutorials on how to set things up correctly, somewhere I must have gone wrong.

**Comment by wesley4546** [comment]
Usually, that means that you need to install the `requests` module. You can do that by going into your terminal and typing `pip install requests`. Do that for all the modules in the `requirements.txt`

I'll look into making a check for that (One of the pros of using an IDE like PyCharm is that it automatically does things like that for you so I haven't run into that problem.)

**Comment by ckfchampion** [comment]
Got it to work! Wohoo! I followed your advice, the new `requirements.txt` from the bug fixing seemed to be a lot more? In any case, for some of the requirements I got `ERROR: Could not find a version that satisfies the requirement` and either had to downgrade or remove from the file. In the end it worked. I see the search is limited to 20 videos correct?

**Comment by wesley4546** [comment]
Great! As long as it is working then I'm sure using older packages is fine (I hope).

I haven't changed the number of videos returned (in fact it is automatic; it only returns what it can) so I think it'll vary depending on the search.

I'm going to close this issue now since we solved the problem but feel free to open another issue if you encounter a bug or any other issues you might have!
